// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibmvsycsslzielofqewg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlibXZzeWNzc2x6aWVsb2ZxZXdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2NjQyNTQsImV4cCI6MjA1OTI0MDI1NH0.GwmxooI2ayalx7tjmlJ_vqiQaSNV5QF4ExYLT36tI9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);